language: java
jdk: oraclejdk8
install: true
script: mvn install -P skip-online-tests
cache:
  directories:
  - $HOME/.m2
notifications:
  email:
    recipients:
      - nkr@niklakr.dk
    on_success: never
    on_failure: always